name: Build and Publish

on:
    release:
        types: [published]

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v6

            - name: Set the version from the release tag
              run: |
                  RELEASE_TAG=${GITHUB_REF#refs/tags/}
                  uv version "${RELEASE_TAG#v}"

            - name: Test
              run: uv run --python 3.11 pytest

            - name: Build package
              run: uv build

            - name: Publish to PyPI
              env:
                  UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
              run: uv publish
